# Generated by Django 5.0.3 on 2024-06-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0003_biodata_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '1. Biodata'},
        ),
    ]
